name: flutter_gen_l10n_example
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  provider: ^6.1.2


 
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  generate: true


  uses-material-design: true



  assets:
    - assets/images/unsplash_eggs.jpg
    - assets/images/unsplash_rice.jpg
    - assets/images/unsplash_salad.jpg

 